name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  minitest:
    runs-on: macos-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        run: bundle exec ruby test/refurb_radar_test.rb
